#!/bin/sh
#
# sshd        Starts sshd.
#

umask 077

testlist="timers"
#testlist="syscalls,fs_perms_simple,fsx,mm,ipc,sched,pty,fcntl-locktests,connectors,admin_tools,timers,modules,pipes"

case "$1" in
  start)
	mkdir /usr/lib/ltp-testsuite/result
	/usr/lib/ltp-testsuite/runltp -f $testlist -p -l /usr/lib/ltp-testsuite/result/ltp.sum -o /usr/lib/ltp-testsuite/result/ltp.log
	ls /usr/lib/ltp-testsuite/result
        echo "==================LTP sum start==================="
        cat /usr/lib/ltp-testsuite/result/ltp.sum
        echo "==================LTP sum end====================="
	echo "==================LTP log start==================="
	cat /usr/lib/ltp-testsuite/result/ltp.log
	echo "==================LTP log end====================="
	poweroff
	;;
  stop)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

